apiVersion: networking.sealos.io/v1alpha1
kind: TrafficSyncRequest
metadata:
  labels:
    app.kubernetes.io/name: trafficsyncrequest
    app.kubernetes.io/instance: trafficsyncrequest-sample
    app.kubernetes.io/part-of: nm-k8s-api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nm-k8s-api
  name: trafficsyncrequest-sample
spec:
  # TODO(user): Add fields here
